# Generated by Django 4.0.1 on 2022-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dictionarylist_created_dictionarylist_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarylist',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
