# Generated by Django 4.0.1 on 2022-02-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-updated', '-created'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
