# Generated by Django 4.0.1 on 2022-02-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dictionarylist_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dictionarylist',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
