# Generated by Django 4.0.1 on 2022-02-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hsklevel_alter_dictionarylist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsklevel',
            options={'ordering': ['level']},
        ),
    ]
