# Generated by Django 4.0.1 on 2022-02-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
