# Generated by Django 4.0.1 on 2022-02-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_lesson_hsklevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('questions', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(help_text='duration of the quiz in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='required score in %')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
