# Generated by Django 4.0.1 on 2022-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_options_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_points',
            field=models.IntegerField(default=0, help_text='total_points'),
            preserve_default=False,
        ),
    ]
